#!/bin/bash

# Author @s4vitar (Marcelo Vázquez)

function extractPorts(){
	echo -e "\n${yellowColour}[*] Extracting Information...${endColour}\n"

	ip_address=$(cat allPorts | grep -oP '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u)
	open_ports=$(cat allPorts| grep -oP '[0-9]{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr ' ' ',')

	echo -e "\t${blueColour}[*] IP Address: ${endColour}${grayColour}$ip_address${endColour}"
	echo -e "\t${blueColour}[*] Open ports: ${endColour}${grayColour}$open_ports${endColour}\n"

	echo $open_ports | tr -d '\n'| xclip -sel clip

	echo -e "${yellowColour}[*] Ports has been copied to clipboard!${endColour}\n"

}

extractPorts
